### ISSUE TITLE
Feature: multi monitor option

### ISSUE THREAD

**Issue by MisteryMonster** [shayne/PowerDimmer#4]
~~Currently the second monitor are not effected at all~~, and need to considering how multi monitor should work. Dimming per monitor independently or just dim out all monitor but the focus window (maybe keep both as an option).

**Comment by shayne** [comment]
This is a regression from my recent commit, take a look at the conversation here:
https://github.com/shayne/PowerDimmer/commit/2c5b3f20a7df55fdf85a9ce4e0d091cdde32a5f2

Will get this fixed ASAP. Multi-mon / DPI was working great before.

**Comment by shayne** [comment]
Should be fixed with latest commit. Give it a go!

**Comment by charlau** [comment]
Hi, I don't know if adding a comment will reopen the issue, but for me, with either the executable or doing a `dotnet run` on a cloned repo, it only works on the main monitor. Otherwise, it is so perfect, I've been looking for this for so long. I don't understand there's no other option out there for this feature, and I really think this should be included in PowerToys! (I only found 1 - commercial - option, and it really isn't much good.)

**Your app is a godsent for ADHDers!**

**Comment by shtuseriff** [comment]
I'm having the multi-monitor issue as well. Unfortunately, I don't want to set the external monitor to be the primary monitor like the above commenter did. Any other solution for getting it to dim windows on external monitor as well? Thank you

**Comment by shtuseriff** [comment]
> Ah, found a workaround! If I set the external display as the main display, it works on both :)
> 
>

I just forked the repo and vibe coded the multi-monitor fix. And also made multi monitor dimming optional. Not sure if this repo is abandoned or what. If not, Just let me know and I'm happy to push the changes upstream instead. If anyone else ends up here like me looking for a fix for this, [https://github.com/shtuseriff/PowerDimmer](https://github.com/shtuseriff/PowerDimmer)
